/**
 * VECTRONOMY — Output Compiler Module
 * 
 * Assembles all resolved elements into finalized SVG documents.
 * Handles layer grouping, viewBox calculation, DPI normalization,
 * and proper SVG namespace output.
 */

import { SceneGraph, ResolvedLayer, ResolvedElement } from './sceneGraph';
import { VectorFactory, parseColor } from './vectorFactory';
import { Transform } from './transform';
import type { XcsCanvas, ConvertedLayer, BBox } from './types';

/** DPI constants */
const XCS_DPI = 96;
const ILLUSTRATOR_DPI = 72;
const MM_PER_INCH = 25.4;

export interface CompilerOptions {
  /** Target DPI for output dimensions (default: 96) */
  targetDpi?: number;
  /** Add padding around the viewBox in user units (default: 5) */
  viewBoxPadding?: number;
  /** Include layer visibility attribute (default: true) */
  respectLayerVisibility?: boolean;
  /** Include metadata comments in output (default: false) */
  includeMetadata?: boolean;
  /** Output physical dimensions in mm (default: true) */
  usePhysicalUnits?: boolean;
}

export class OutputCompiler {
  /**
   * Compile a single XCS canvas into an array of converted SVG layers.
   * Each layer contains its own complete SVG document.
   */
  static compileCanvas(
    canvas: XcsCanvas,
    options: CompilerOptions = {}
  ): ConvertedLayer[] {
    const {
      targetDpi = XCS_DPI,
      viewBoxPadding = 5,
      respectLayerVisibility = true,
      includeMetadata = false,
      usePhysicalUnits = true,
    } = options;

    // Build scene graph
    const graph = new SceneGraph(canvas);
    const layers = graph.resolveAll();
    const bbox = graph.calculateBoundingBox();

    // Apply padding to bounding box
    const paddedBBox: BBox = {
      minX: bbox.minX - viewBoxPadding,
      minY: bbox.minY - viewBoxPadding,
      maxX: bbox.maxX + viewBoxPadding,
      maxY: bbox.maxY + viewBoxPadding,
      width: bbox.width + viewBoxPadding * 2,
      height: bbox.height + viewBoxPadding * 2,
    };

    // Calculate DPI scaling factor
    const dpiScale = targetDpi / XCS_DPI;

    // Generate combined SVG with all layers as groups
    const combinedSvg = OutputCompiler.generateCombinedSvg(
      layers,
      paddedBBox,
      dpiScale,
      respectLayerVisibility,
      includeMetadata,
      usePhysicalUnits
    );

    // Also generate individual layer outputs
    const result: ConvertedLayer[] = [];

    // Combined layer
    result.push({
      id: canvas.id || 'combined',
      name: OutputCompiler.formatCanvasTitle(canvas.title),
      color: '#00ffc2',
      svg: combinedSvg,
      elementCount: layers.reduce((sum, l) => sum + l.elements.length, 0),
    });

    return result;
  }

  /**
   * Compile all canvases from an XCS file.
   */
  static compileAll(
    canvases: XcsCanvas[],
    options: CompilerOptions = {}
  ): ConvertedLayer[] {
    const allLayers: ConvertedLayer[] = [];

    for (const canvas of canvases) {
      const layers = OutputCompiler.compileCanvas(canvas, options);
      allLayers.push(...layers);
    }

    return allLayers;
  }

  /**
   * Generate a combined SVG with all layers as <g> groups.
   */
  private static generateCombinedSvg(
    layers: ResolvedLayer[],
    bbox: BBox,
    dpiScale: number,
    respectVisibility: boolean,
    includeMetadata: boolean,
    usePhysicalUnits: boolean
  ): string {
    const viewBox = `${bbox.minX} ${bbox.minY} ${bbox.width} ${bbox.height}`;
    const { widthAttr, heightAttr } = OutputCompiler.computeDimensions(
      bbox,
      dpiScale,
      usePhysicalUnits
    );

    const parts: string[] = [];

    parts.push(
      `<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%">`
    );

    // Add pattern definitions for hatching
    const defs = OutputCompiler.generateDefs(layers);
    if (defs) parts.push(defs);

    parts.push(`  <g id="viewport">`);

    if (includeMetadata) {
      parts.push(`  <!-- Generated by VECTRONOMY XCS→SVG Engine -->`);
      parts.push(`  <!-- Layers: ${layers.length} -->`);
    }

    // Render each layer as a group
    for (const layer of layers) {
      const visibility =
        respectVisibility && !layer.visible ? ' display="none"' : '';
      parts.push(
        `  <g class="layer" id="layer-${OutputCompiler.sanitizeId(layer.id)}" data-name="${OutputCompiler.escapeXml(layer.name)}"${visibility}>`
      );

      // Group elements by their root cluster for proper nesting
      const rendered = OutputCompiler.renderLayerElements(layer);
      parts.push(rendered);

      parts.push(`  </g>`);
    }

    parts.push(`  </g>\n</svg>`);
    return parts.join('\n');
  }

  /**
   * Generate an individual layer SVG document.
   */
  private static generateLayerSvg(
    layer: ResolvedLayer,
    bbox: BBox,
    dpiScale: number,
    includeMetadata: boolean,
    usePhysicalUnits: boolean
  ): string {
    const viewBox = `${bbox.minX} ${bbox.minY} ${bbox.width} ${bbox.height}`;
    const { widthAttr, heightAttr } = OutputCompiler.computeDimensions(
      bbox,
      dpiScale,
      usePhysicalUnits
    );

    const parts: string[] = [];
    parts.push(
      `<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%">`
    );

    // Add pattern definitions for hatching
    const defs = OutputCompiler.generateDefs([layer]);
    if (defs) parts.push(defs);

    parts.push(`  <g id="viewport">`);

    if (includeMetadata) {
      parts.push(`  <!-- Layer: ${layer.name} -->`);
    }

    const rendered = OutputCompiler.renderLayerElements(layer);
    parts.push(rendered);

    parts.push(`  </g>\n</svg>`);
    return parts.join('\n');
  }

  /**
   * Render all elements in a layer, grouped by their root clusters.
   * Elements sharing the same root ancestor are wrapped in a single <g>.
   */
  private static renderLayerElements(layer: ResolvedLayer): string {
    const clusters = new Map<string, ResolvedElement[]>();

    for (const el of layer.elements) {
      const rid = el.rootId || 'null';
      if (!clusters.has(rid)) clusters.set(rid, []);
      clusters.get(rid)!.push(el);
    }

    const parts: string[] = [];

    for (const [rootId, elements] of clusters) {
      const clusterParts: string[] = [];
      
      for (const el of elements) {
        // We generate each element individually to ensure it has its own ID and is selectable
        const svgStr = VectorFactory.generateElement(el.display, el.worldTransform);
        if (svgStr) {
          const xcsId = el.display.id;
          const wrappedSvg = svgStr.replace(
            /^<([^ >]+)/,
            `<$1 data-xcs-id="${xcsId}"`
          );
          clusterParts.push(wrappedSvg);
        }
      }

      if (rootId && rootId !== 'null') {
        const xcsId = rootId.startsWith('g-') ? rootId.substring(2) : rootId;
        parts.push(`    <g id="cluster-${OutputCompiler.sanitizeId(rootId)}" data-xcs-id="${xcsId}" fill-rule="nonzero">`);
        for (const p of clusterParts) {
          parts.push(`      ${p}`);
        }
        parts.push(`    </g>`);
      } else {
        parts.push(clusterParts.map(p => `    ${p}`).join('\n'));
      }
    }

    return parts.join('\n');
  }

  /**
   * Generate <defs> containing <pattern> elements for any hatching fills used.
   */
  private static generateDefs(layers: ResolvedLayer[]): string {
    const defs: string[] = [];
    const seenHatchIds = new Set<string>();
    const seenMaskIds = new Set<string>();

    for (const layer of layers) {
      for (const el of layer.elements) {
        // 1. Hatching
        if (el.display.fill?.paintType === 'hatch') {
          const hatchId = `hatch-${el.display.id}`;
          if (!seenHatchIds.has(hatchId)) {
            seenHatchIds.add(hatchId);
            const color = el.display.fillColor ? parseColor(el.display.fillColor) : '#000000';
            defs.push(
              `    <pattern id="${hatchId}" patternUnits="userSpaceOnUse" width="4" height="4" patternTransform="rotate(45)">`,
              `      <line x1="0" y1="0" x2="0" y2="4" stroke="${color}" stroke-width="0.5" />`,
              `    </pattern>`
            );
          }
        }

        // 2. Masks
        if (el.display.mask) {
          const mask = el.display.mask;
          const maskId = `mask-${mask.id}`;
          if (!seenMaskIds.has(maskId)) {
            seenMaskIds.add(maskId);
            defs.push(VectorFactory.generateClipPath(mask, maskId));
          }
        }
      }
    }

    if (defs.length === 0) return '';
    return `  <defs>\n${defs.join('\n')}\n  </defs>`;
  }

  /**
   * Compute SVG width/height attributes with DPI normalization.
   */
  private static computeDimensions(
    bbox: BBox,
    dpiScale: number,
    usePhysicalUnits: boolean
  ): { widthAttr: string; heightAttr: string } {
    if (usePhysicalUnits) {
      // Convert from 96DPI user units to mm
      const widthMm = (bbox.width / XCS_DPI) * MM_PER_INCH * dpiScale;
      const heightMm = (bbox.height / XCS_DPI) * MM_PER_INCH * dpiScale;
      return {
        widthAttr: `${widthMm.toFixed(2)}mm`,
        heightAttr: `${heightMm.toFixed(2)}mm`,
      };
    }

    // Pixel dimensions
    const w = bbox.width * dpiScale;
    const h = bbox.height * dpiScale;
    return {
      widthAttr: `${w.toFixed(2)}`,
      heightAttr: `${h.toFixed(2)}`,
    };
  }

  /**
   * Format canvas title, replacing {panel} placeholder.
   */
  private static formatCanvasTitle(title?: string): string {
    if (!title) return 'Untitled Panel';
    return title.replace('{panel}', 'Panel ');
  }

  /**
   * Sanitize an ID for use in SVG attributes.
   */
  private static sanitizeId(id: string): string {
    return id.replace(/[^a-zA-Z0-9_-]/g, '_');
  }

  /**
   * Escape XML special characters.
   */
  private static escapeXml(str: string): string {
    return str
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&apos;');
  }
}
